@startuml
class SqlSeedDataAccessor {
    + SqlSeedDataAccessor(connectionString:string)
    + CreateCatalog(sellerId:int, catalogName:string) : int
    + CreateProduct(catalogId:int, name:string, isAvailable:bool, isDownloadable:bool, summary:string, detail:string, supplier:string, price:decimal) : int
    + CreateSeller(username:string, sellerName:string) : int
    + Dispose() : void
}
ISeedDataAccessor <|-- SqlSeedDataAccessor
SqlSeedDataAccessor --> "_connection" SqlConnection
@enduml
