@startuml
abstract class DbTestAccessorBase {
    + DbTestAccessorBase()
    + Init() : void
    + Cleanup() : void
    + {static} CreateGlobalContext() : void
    + {static} CancelGlobalTransaction() : void
}
@enduml
