@startuml
class EmailFormattingEngine {
    + FormatOrderEmailBody(order:Order, seller:Seller) : string
}
EngineBase <|-- EmailFormattingEngine
IEmailFormattingEngine <|-- EmailFormattingEngine
@enduml
