@startuml
interface ICartAccessor {
    ShowCart(catalogId:int) : Cart
    SaveBillingInfo(catalogId:int, billingAddress:Address) : Cart
    SaveShippingInfo(catalogId:int, shippingAddress:Address) : Cart
    SaveCartItem(catalogId:int, productId:int, quantity:int) : Cart
    DeleteCart(catalogId:int) : bool
}
IServiceContractBase <|-- ICartAccessor
@enduml
