@startuml
class NotificationManager {
    + <<override>> TestMe(input:string) : string
    + SendNewOrderNotices(orderId:int) : NotificationResponse
    + SendOrderFulfillmentNotices(orderId:int) : NotificationResponse
}
ManagerBase <|-- NotificationManager
INotificationManager <|-- NotificationManager
@enduml
