@startuml
abstract class IntegrationTestBase {
    + IntegrationTestBase()
    + Init() : void
    + Cleanup() : void
    + {static} CreateGlobalContext() : void
    + {static} CancelGlobalTransaction() : void
}
@enduml
