@startuml
!include .\\DPLRef.eCommerce.Accessors\AccessorBase.puml
!include .\\DPLRef.eCommerce.Accessors\AccessorFactory.puml
!include .\\DPLRef.eCommerce.Accessors\DTOMapper.puml
!include .\\DPLRef.eCommerce.Client.Admin\BaseUICommand.puml
!include .\\DPLRef.eCommerce.Client.Admin\CreateCatalogCommand.puml
!include .\\DPLRef.eCommerce.Client.Admin\CreateProductCommand.puml
!include .\\DPLRef.eCommerce.Client.Admin\FindCatalogsCommand.puml
!include .\\DPLRef.eCommerce.Client.Admin\FulfillOrderCommand.puml
!include .\\DPLRef.eCommerce.Client.Admin\OrdersToFulfillCommand.puml
!include .\\DPLRef.eCommerce.Client.Admin\Program.puml
!include .\\DPLRef.eCommerce.Client.Admin\QueryWithBadTokenCommand.puml
!include .\\DPLRef.eCommerce.Client.Admin\ShowCatalogCommand.puml
!include .\\DPLRef.eCommerce.Client.Admin\ShowProductCommand.puml
!include .\\DPLRef.eCommerce.Client.Admin\TotalsCommand.puml
!include .\\DPLRef.eCommerce.Client.Admin\UICommandParameter.puml
!include .\\DPLRef.eCommerce.Client.BackOfficeAdmin\Program.puml
!include .\\DPLRef.eCommerce.Client.BackOfficeAdmin\TotalsCommand.puml
!include .\\DPLRef.eCommerce.Client.WebStore\Program.puml
!include .\\DPLRef.eCommerce.Common.Contracts\Address.puml
!include .\\DPLRef.eCommerce.Common.Contracts\AmbientContext.puml
!include .\\DPLRef.eCommerce.Common.Contracts\AsyncEventTypes.puml
!include .\\DPLRef.eCommerce.Common.Contracts\OrderStatuses.puml
!include .\\DPLRef.eCommerce.Common.Contracts\PaymentInstrument.puml
!include .\\DPLRef.eCommerce.Common.Shared\Config.puml
!include .\\DPLRef.eCommerce.Common.Shared\DTOPropCopy.puml
!include .\\DPLRef.eCommerce.Common.Shared\FactoryBase.puml
!include .\\DPLRef.eCommerce.Common.Shared\IServiceContractBase.puml
!include .\\DPLRef.eCommerce.Common.Shared\Logger.puml
!include .\\DPLRef.eCommerce.Common.Shared\ResponseBase.puml
!include .\\DPLRef.eCommerce.Common.Shared\ServiceContractBase.puml
!include .\\DPLRef.eCommerce.Common.Shared\StringUtilities.puml
!include .\\DPLRef.eCommerce.Contracts.Admin\WebStoreCatalog.puml
!include .\\DPLRef.eCommerce.Database\ISeedDataAccessor.puml
!include .\\DPLRef.eCommerce.Database\Program.puml
!include .\\DPLRef.eCommerce.Database\SeedDataManager.puml
!include .\\DPLRef.eCommerce.Database\SqliteSeedDataAccessor.puml
!include .\\DPLRef.eCommerce.Database\SqlSeedDataAccessor.puml
!include .\\DPLRef.eCommerce.Engines\DTOMapper.puml
!include .\\DPLRef.eCommerce.Engines\EngineBase.puml
!include .\\DPLRef.eCommerce.Engines\EngineFactory.puml
!include .\\DPLRef.eCommerce.Managers\DTOMapper.puml
!include .\\DPLRef.eCommerce.Managers\ManagerBase.puml
!include .\\DPLRef.eCommerce.Managers\ManagerFactory.puml
!include .\\DPLRef.eCommerce.Service.Notifications\Program.puml
!include .\\DPLRef.eCommerce.Tests.AccessorTests\CartAccessorTests.puml
!include .\\DPLRef.eCommerce.Tests.AccessorTests\CatalogAccessorTests.puml
!include .\\DPLRef.eCommerce.Tests.AccessorTests\DataValidation.puml
!include .\\DPLRef.eCommerce.Tests.AccessorTests\DbTestAccessorBase.puml
!include .\\DPLRef.eCommerce.Tests.AccessorTests\DTOMapperTests.puml
!include .\\DPLRef.eCommerce.Tests.AccessorTests\EmailAccessorTests.puml
!include .\\DPLRef.eCommerce.Tests.AccessorTests\OrderAccessorTests.puml
!include .\\DPLRef.eCommerce.Tests.AccessorTests\PaymentAccessorTests.puml
!include .\\DPLRef.eCommerce.Tests.AccessorTests\RemittanceAccessorTests.puml
!include .\\DPLRef.eCommerce.Tests.AccessorTests\SellerAccessorTests.puml
!include .\\DPLRef.eCommerce.Tests.AccessorTests\ShippingAccessorTests.puml
!include .\\DPLRef.eCommerce.Tests.AccessorTests\TaxAccesorTests.puml
!include .\\DPLRef.eCommerce.Tests.EngineTests\DTOMapperTests.puml
!include .\\DPLRef.eCommerce.Tests.EngineTests\EmailFormattingEngineTests.puml
!include .\\DPLRef.eCommerce.Tests.EngineTests\EngineTestBase.puml
!include .\\DPLRef.eCommerce.Tests.EngineTests\PricingEngineTests.puml
!include .\\DPLRef.eCommerce.Tests.EngineTests\RemittanceCalculationEngineTests.puml
!include .\\DPLRef.eCommerce.Tests.EngineTests\TaxCalculationEngineTests.puml
!include .\\DPLRef.eCommerce.Tests.EngineTests\ValidationEngineTests.puml
!include .\\DPLRef.eCommerce.Tests.IntegrationTests\AdminTests.puml
!include .\\DPLRef.eCommerce.Tests.IntegrationTests\IntegrationTestBase.puml
!include .\\DPLRef.eCommerce.Tests.IntegrationTests\WebstoreTests.puml
!include .\\DPLRef.eCommerce.Tests.ManagerTests\CartManagerTests.puml
!include .\\DPLRef.eCommerce.Tests.ManagerTests\CatalogManagerTests.puml
!include .\\DPLRef.eCommerce.Tests.ManagerTests\DTOMapperTests.puml
!include .\\DPLRef.eCommerce.Tests.ManagerTests\FulfillmentManagerTests.puml
!include .\\DPLRef.eCommerce.Tests.ManagerTests\ManagerTestBase.puml
!include .\\DPLRef.eCommerce.Tests.ManagerTests\NotificationManagerTests.puml
!include .\\DPLRef.eCommerce.Tests.ManagerTests\OrderManagerTests.puml
!include .\\DPLRef.eCommerce.Tests.ManagerTests\RemittanceManagerTests.puml
!include .\\DPLRef.eCommerce.Tests.Mocks\MockAsyncUtility.puml
!include .\\DPLRef.eCommerce.Tests.Mocks\MockBase.puml
!include .\\DPLRef.eCommerce.Tests.Mocks\MockCartAccessor.puml
!include .\\DPLRef.eCommerce.Tests.Mocks\MockCatalogAccessor.puml
!include .\\DPLRef.eCommerce.Tests.Mocks\MockData.puml
!include .\\DPLRef.eCommerce.Tests.Mocks\MockOrderAccessor.puml
!include .\\DPLRef.eCommerce.Tests.Mocks\MockPaymentAccessor.puml
!include .\\DPLRef.eCommerce.Tests.Mocks\MockRemittanceAccessor.puml
!include .\\DPLRef.eCommerce.Tests.Mocks\MockSecurityUtility.puml
!include .\\DPLRef.eCommerce.Tests.Mocks\MockSellerAccessor.puml
!include .\\DPLRef.eCommerce.Tests.Mocks\MockShippingAccessor.puml
!include .\\DPLRef.eCommerce.Utilities\AddressUtility.puml
!include .\\DPLRef.eCommerce.Utilities\AsyncQueueItem.puml
!include .\\DPLRef.eCommerce.Utilities\AsyncUtility.puml
!include .\\DPLRef.eCommerce.Utilities\IAddressUtility.puml
!include .\\DPLRef.eCommerce.Utilities\IAsyncUtility.puml
!include .\\DPLRef.eCommerce.Utilities\ISecurityUtility.puml
!include .\\DPLRef.eCommerce.Utilities\SecurityUtility.puml
!include .\\DPLRef.eCommerce.Utilities\UtilityBase.puml
!include .\\DPLRef.eCommerce.Utilities\UtilityFactory.puml
!include .\\DPLRef.eCommerce.Accessors\Catalog\CatalogAccessor.puml
!include .\\DPLRef.eCommerce.Accessors\Catalog\ICatalogAccessor.puml
!include .\\DPLRef.eCommerce.Accessors\DataTransferObjects\Cart.puml
!include .\\DPLRef.eCommerce.Accessors\DataTransferObjects\Order.puml
!include .\\DPLRef.eCommerce.Accessors\DataTransferObjects\PaymentAuthStatusResult.puml
!include .\\DPLRef.eCommerce.Accessors\DataTransferObjects\PaymentCaptureResult.puml
!include .\\DPLRef.eCommerce.Accessors\DataTransferObjects\Product.puml
!include .\\DPLRef.eCommerce.Accessors\DataTransferObjects\Seller.puml
!include .\\DPLRef.eCommerce.Accessors\DataTransferObjects\SellerOrderData.puml
!include .\\DPLRef.eCommerce.Accessors\DataTransferObjects\SellerSalesTotal.puml
!include .\\DPLRef.eCommerce.Accessors\DataTransferObjects\ShippingResult.puml
!include .\\DPLRef.eCommerce.Accessors\DataTransferObjects\WebStoreCatalog.puml
!include .\\DPLRef.eCommerce.Accessors\EntityFramework\Cart.puml
!include .\\DPLRef.eCommerce.Accessors\EntityFramework\CartItem.puml
!include .\\DPLRef.eCommerce.Accessors\EntityFramework\Catalog.puml
!include .\\DPLRef.eCommerce.Accessors\EntityFramework\eCommerceDbContext.puml
!include .\\DPLRef.eCommerce.Accessors\EntityFramework\Order.puml
!include .\\DPLRef.eCommerce.Accessors\EntityFramework\OrderLine.puml
!include .\\DPLRef.eCommerce.Accessors\EntityFramework\Product.puml
!include .\\DPLRef.eCommerce.Accessors\EntityFramework\Seller.puml
!include .\\DPLRef.eCommerce.Accessors\Notifications\EmailAccessor.puml
!include .\\DPLRef.eCommerce.Accessors\Notifications\IEmailAccessor.puml
!include .\\DPLRef.eCommerce.Accessors\Remittance\IRemittanceAccessor.puml
!include .\\DPLRef.eCommerce.Accessors\Remittance\ISellerAccessor.puml
!include .\\DPLRef.eCommerce.Accessors\Remittance\RemittanceAccessor.puml
!include .\\DPLRef.eCommerce.Accessors\Remittance\SellerAccessor.puml
!include .\\DPLRef.eCommerce.Accessors\Sales\CartAccessor.puml
!include .\\DPLRef.eCommerce.Accessors\Sales\ICartAccessor.puml
!include .\\DPLRef.eCommerce.Accessors\Sales\IOrderAccessor.puml
!include .\\DPLRef.eCommerce.Accessors\Sales\IPaymentAccessor.puml
!include .\\DPLRef.eCommerce.Accessors\Sales\IShippingAccessor.puml
!include .\\DPLRef.eCommerce.Accessors\Sales\IShippingRulesAccessor.puml
!include .\\DPLRef.eCommerce.Accessors\Sales\OrderAccessor.puml
!include .\\DPLRef.eCommerce.Accessors\Sales\PaymentAccessor.puml
!include .\\DPLRef.eCommerce.Accessors\Sales\ShippingAccessor.puml
!include .\\DPLRef.eCommerce.Accessors\Sales\ShippingRulesAccessor.puml
!include .\\DPLRef.eCommerce.Accessors\Sales\TaxRateAccessor.puml
!include .\\DPLRef.eCommerce.Contracts.Admin\Catalog\AdminCatalogResponse.puml
!include .\\DPLRef.eCommerce.Contracts.Admin\Catalog\AdminCatalogsResponse.puml
!include .\\DPLRef.eCommerce.Contracts.Admin\Catalog\AdminProductResponse.puml
!include .\\DPLRef.eCommerce.Contracts.Admin\Catalog\IAdminCatalogManager.puml
!include .\\DPLRef.eCommerce.Contracts.Admin\Catalog\Product.puml
!include .\\DPLRef.eCommerce.Contracts.Admin\Catalog\WebStoreCatalog.puml
!include .\\DPLRef.eCommerce.Contracts.Admin\Fulfillment\AdminFulfillmentResponse.puml
!include .\\DPLRef.eCommerce.Contracts.Admin\Fulfillment\AdminOpenOrdersResponse.puml
!include .\\DPLRef.eCommerce.Contracts.Admin\Fulfillment\AdminUnfulfilledOrder.puml
!include .\\DPLRef.eCommerce.Contracts.Admin\Fulfillment\IAdminFulfillmentManager.puml
!include .\\DPLRef.eCommerce.Contracts.Admin\Sales\IAdminRemittanceManager.puml
!include .\\DPLRef.eCommerce.Contracts.Admin\Sales\IReturnsManager.puml
!include .\\DPLRef.eCommerce.Contracts.Admin\Sales\SalesTotalsResponse.puml
!include .\\DPLRef.eCommerce.Contracts.BackOfficeAdmin\Remittance\IBackOfficeRemittanceManager.puml
!include .\\DPLRef.eCommerce.Contracts.BackOfficeAdmin\Remittance\OrderDataResponse.puml
!include .\\DPLRef.eCommerce.Contracts.ServiceHost\Notifications\INotificationManager.puml
!include .\\DPLRef.eCommerce.Contracts.ServiceHost\Notifications\NotificationResponse.puml
!include .\\DPLRef.eCommerce.Contracts.WebStore\Catalog\IWebStoreCatalogManager.puml
!include .\\DPLRef.eCommerce.Contracts.WebStore\Catalog\ProductDetail.puml
!include .\\DPLRef.eCommerce.Contracts.WebStore\Catalog\ProductSummary.puml
!include .\\DPLRef.eCommerce.Contracts.WebStore\Catalog\WebStoreCatalog.puml
!include .\\DPLRef.eCommerce.Contracts.WebStore\Catalog\WebStoreCatalogResponse.puml
!include .\\DPLRef.eCommerce.Contracts.WebStore\Catalog\WebStoreProductResponse.puml
!include .\\DPLRef.eCommerce.Contracts.WebStore\Sales\IWebStoreCartManager.puml
!include .\\DPLRef.eCommerce.Contracts.WebStore\Sales\IWebStoreOrderManager.puml
!include .\\DPLRef.eCommerce.Contracts.WebStore\Sales\WebstoreCart.puml
!include .\\DPLRef.eCommerce.Contracts.WebStore\Sales\WebStoreCartResponse.puml
!include .\\DPLRef.eCommerce.Contracts.WebStore\Sales\WebStoreOrder.puml
!include .\\DPLRef.eCommerce.Contracts.WebStore\Sales\WebStoreOrderResponse.puml
!include .\\DPLRef.eCommerce.Engines\Notification\EmailFormattingEngine.puml
!include .\\DPLRef.eCommerce.Engines\Notification\IEmailFormattingEngine.puml
!include .\\DPLRef.eCommerce.Engines\Remmitance\IRemittanceCalculationEngine.puml
!include .\\DPLRef.eCommerce.Engines\Remmitance\RemittanceCalculationEngine.puml
!include .\\DPLRef.eCommerce.Engines\Remmitance\RemittanceCalculationResult.puml
!include .\\DPLRef.eCommerce.Engines\Sales\ICartPricingEngine.puml
!include .\\DPLRef.eCommerce.Engines\Sales\IOrderValidationEngine.puml
!include .\\DPLRef.eCommerce.Engines\Sales\ITaxCalculationEngine.puml
!include .\\DPLRef.eCommerce.Engines\Sales\PricingEngine.puml
!include .\\DPLRef.eCommerce.Engines\Sales\TaxCalculationEngine.puml
!include .\\DPLRef.eCommerce.Engines\Sales\ValidationEngine.puml
!include .\\DPLRef.eCommerce.Engines\Sales\ValidationResponse.puml
!include .\\DPLRef.eCommerce.Managers\Catalog\CatalogManager.puml
!include .\\DPLRef.eCommerce.Managers\Notification\NotificationManager.puml
!include .\\DPLRef.eCommerce.Managers\Remittance\RemittanceManager.puml
!include .\\DPLRef.eCommerce.Managers\Sales\OrderManager.puml
!include .\\DPLRef.eCommerce.Tests.IntegrationTests\ExpectedResponses\AdminResponses.puml
!include .\\DPLRef.eCommerce.Tests.IntegrationTests\ExpectedResponses\WebstoreResponses.puml
!include .\\_Documentation\Design\Scratchpad.puml
!include .\\DPLRef.eCommerce.Accessors\obj\Debug\net5.0\.NETCoreApp,Version=v5.0.AssemblyAttributes.puml
!include .\\DPLRef.eCommerce.Accessors\obj\Debug\net5.0\DPLRef.eCommerce.Accessors.AssemblyInfo.puml
!include .\\DPLRef.eCommerce.Client.Admin\obj\Debug\net5.0\.NETCoreApp,Version=v5.0.AssemblyAttributes.puml
!include .\\DPLRef.eCommerce.Client.Admin\obj\Debug\net5.0\DPLRef.eCommerce.Client.Admin.AssemblyInfo.puml
!include .\\DPLRef.eCommerce.Client.BackOfficeAdmin\obj\Debug\net5.0\.NETCoreApp,Version=v5.0.AssemblyAttributes.puml
!include .\\DPLRef.eCommerce.Client.BackOfficeAdmin\obj\Debug\net5.0\DPLRef.eCommerce.Client.BackOfficeAdmin.AssemblyInfo.puml
!include .\\DPLRef.eCommerce.Client.WebStore\obj\Debug\net5.0\.NETCoreApp,Version=v5.0.AssemblyAttributes.puml
!include .\\DPLRef.eCommerce.Client.WebStore\obj\Debug\net5.0\DPLRef.eCommerce.Client.WebStore.AssemblyInfo.puml
!include .\\DPLRef.eCommerce.Common.Contracts\obj\Debug\netstandard2.0\.NETStandard,Version=v2.0.AssemblyAttributes.puml
!include .\\DPLRef.eCommerce.Common.Contracts\obj\Debug\netstandard2.0\DPLRef.eCommerce.Common.Contracts.AssemblyInfo.puml
!include .\\DPLRef.eCommerce.Common.Contracts\obj\Release\netstandard2.0\.NETStandard,Version=v2.0.AssemblyAttributes.puml
!include .\\DPLRef.eCommerce.Common.Contracts\obj\Release\netstandard2.0\DPLRef.eCommerce.Common.Contracts.AssemblyInfo.puml
!include .\\DPLRef.eCommerce.Common.Shared\obj\Debug\netstandard2.0\.NETStandard,Version=v2.0.AssemblyAttributes.puml
!include .\\DPLRef.eCommerce.Common.Shared\obj\Debug\netstandard2.0\DPLRef.eCommerce.Common.Shared.AssemblyInfo.puml
!include .\\DPLRef.eCommerce.Common.Shared\obj\Release\netstandard2.0\.NETStandard,Version=v2.0.AssemblyAttributes.puml
!include .\\DPLRef.eCommerce.Common.Shared\obj\Release\netstandard2.0\DPLRef.eCommerce.Common.Shared.AssemblyInfo.puml
!include .\\DPLRef.eCommerce.Contracts.Admin\obj\Debug\net5.0\.NETCoreApp,Version=v5.0.AssemblyAttributes.puml
!include .\\DPLRef.eCommerce.Contracts.Admin\obj\Debug\net5.0\DPLRef.eCommerce.Contracts.Admin.AssemblyInfo.puml
!include .\\DPLRef.eCommerce.Contracts.BackOfficeAdmin\obj\Debug\net5.0\.NETCoreApp,Version=v5.0.AssemblyAttributes.puml
!include .\\DPLRef.eCommerce.Contracts.BackOfficeAdmin\obj\Debug\net5.0\DPLRef.eCommerce.Contracts.BackOfficeAdmin.AssemblyInfo.puml
!include .\\DPLRef.eCommerce.Contracts.ServiceHost\obj\Debug\net5.0\.NETCoreApp,Version=v5.0.AssemblyAttributes.puml
!include .\\DPLRef.eCommerce.Contracts.ServiceHost\obj\Debug\net5.0\DPLRef.eCommerce.Contracts.ServiceHost.AssemblyInfo.puml
!include .\\DPLRef.eCommerce.Contracts.WebStore\obj\Debug\net5.0\.NETCoreApp,Version=v5.0.AssemblyAttributes.puml
!include .\\DPLRef.eCommerce.Contracts.WebStore\obj\Debug\net5.0\DPLRef.eCommerce.Contracts.WebStore.AssemblyInfo.puml
!include .\\DPLRef.eCommerce.Database\obj\Debug\net5.0\.NETCoreApp,Version=v5.0.AssemblyAttributes.puml
!include .\\DPLRef.eCommerce.Database\obj\Debug\net5.0\DPLRef.eCommerce.Database.AssemblyInfo.puml
!include .\\DPLRef.eCommerce.Engines\obj\Debug\net5.0\.NETCoreApp,Version=v5.0.AssemblyAttributes.puml
!include .\\DPLRef.eCommerce.Engines\obj\Debug\net5.0\DPLRef.eCommerce.Engines.AssemblyInfo.puml
!include .\\DPLRef.eCommerce.Managers\obj\Debug\net5.0\.NETCoreApp,Version=v5.0.AssemblyAttributes.puml
!include .\\DPLRef.eCommerce.Managers\obj\Debug\net5.0\DPLRef.eCommerce.Managers.AssemblyInfo.puml
!include .\\DPLRef.eCommerce.Service.Notifications\obj\Debug\net5.0\.NETCoreApp,Version=v5.0.AssemblyAttributes.puml
!include .\\DPLRef.eCommerce.Service.Notifications\obj\Debug\net5.0\DPLRef.eCommerce.Service.Notifications.AssemblyInfo.puml
!include .\\DPLRef.eCommerce.Tests.AccessorTests\obj\Debug\net5.0\.NETCoreApp,Version=v5.0.AssemblyAttributes.puml
!include .\\DPLRef.eCommerce.Tests.AccessorTests\obj\Debug\net5.0\DPLRef.eCommerce.Tests.AccessorTests.AssemblyInfo.puml
!include .\\DPLRef.eCommerce.Tests.EngineTests\obj\Debug\net5.0\.NETCoreApp,Version=v5.0.AssemblyAttributes.puml
!include .\\DPLRef.eCommerce.Tests.EngineTests\obj\Debug\net5.0\DPLRef.eCommerce.Tests.EngineTests.AssemblyInfo.puml
!include .\\DPLRef.eCommerce.Tests.IntegrationTests\obj\Debug\net5.0\.NETCoreApp,Version=v5.0.AssemblyAttributes.puml
!include .\\DPLRef.eCommerce.Tests.IntegrationTests\obj\Debug\net5.0\DPLRef.eCommerce.Tests.IntegrationTests.AssemblyInfo.puml
!include .\\DPLRef.eCommerce.Tests.ManagerTests\obj\Debug\net5.0\.NETCoreApp,Version=v5.0.AssemblyAttributes.puml
!include .\\DPLRef.eCommerce.Tests.ManagerTests\obj\Debug\net5.0\DPLRef.eCommerce.Tests.ManagerTests.AssemblyInfo.puml
!include .\\DPLRef.eCommerce.Tests.Mocks\obj\Debug\net5.0\.NETCoreApp,Version=v5.0.AssemblyAttributes.puml
!include .\\DPLRef.eCommerce.Tests.Mocks\obj\Debug\net5.0\DPLRef.eCommerce.Tests.Mocks.AssemblyInfo.puml
!include .\\DPLRef.eCommerce.Utilities\obj\Debug\net5.0\.NETCoreApp,Version=v5.0.AssemblyAttributes.puml
!include .\\DPLRef.eCommerce.Utilities\obj\Debug\net5.0\DPLRef.eCommerce.Utilities.AssemblyInfo.puml
@enduml
