@startuml
class QueryWithBadTokenCommand {
    + QueryWithBadTokenCommand(ambientContext:AmbientContext)
    + <<override>> Name : string <<get>>
}
BaseUICommand <|-- QueryWithBadTokenCommand
@enduml
