@startuml
class SellerOrderData {
    + SellerId : int <<get>> <<set>>
    + SellerName : string <<get>> <<set>>
    + OrderCount : int <<get>> <<set>>
    + OrderTotal : decimal <<get>> <<set>>
}
@enduml
