@startuml
interface IAdminFulfillmentManager {
    GetOrdersToFulfill() : AdminOpenOrdersResponse
    FulfillOrder(orderId:int) : AdminFulfillmentResponse
}
IServiceContractBase <|-- IAdminFulfillmentManager
@enduml
