@startuml
interface IWebStoreCatalogManager {
    ShowCatalog(catalogId:int) : WebStoreCatalogResponse
    ShowProduct(catalogId:int, productId:int) : WebStoreProductResponse
}
IServiceContractBase <|-- IWebStoreCatalogManager
@enduml
